<h2><?= $this->escapeHtml($this->ticket->assunto) ?></h2>
<h2 class="text-danger">Atenção</h2>
<p>Ao deletar o ticket<strong>todos os arquivos e interações relacionados</strong> serão excluidos.</p>
<p>Tem certeza que deseja deletar este ticket?</p>

<?php echo $this->form()->openTag($this->form); ?>
<?php echo $this->formHidden($this->form->get('csrf'));?>
    <div class="card-footer">
        <button type="submit" class="btn btn-danger"><i class="mdi mdi-trash-can"></i></button>
    </div>
<?php echo $this->form()->closeTag($this->form); ?>
