<div class="row w-100 mx-0">
    <div class="col-lg-4 mx-auto">
        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
            <div class="brand-logo">
                <img src="../../images/logo.svg" alt="logo">
            </div>
            <h4>Hello! let's get started</h4>
            <h6 class="font-weight-light">Sign in to continue.</h6>
            <?php
            echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
            echo $this->flashMessenger()->render('success', ['alert alert-success alert-dismissible']);
            echo $this->flashMessenger()->render('info', ['alert alert-info alert-dismissible']);
            ?>
            <?php echo $this->form()->openTag($this->form); ?>
                <?php echo $this->formHidden($this->form->get('csrf'));?>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('email')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('email')->getLabel();?>
                    <?php echo $this->formEmail($this->form->get('email'));?>
                    <?php echo $this->formElementErrors($this->form->get('email')); ?>
                </div>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('password')) ? 'has-error' : ''; ?> has-feedback">
                <?php echo $this->form->get('password')->getLabel();?>
                    <?php echo $this->formPassword($this->form->get('password'));?>
                    <?php echo $this->formElementErrors($this->form->get('password')); ?>
                </div>
                <div class="mt-3">
                    <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" href="../../index.html" type="submit" value="SIGN IN">
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                    <div class="form-check">
                        <label class="form-check-label text-muted">
                            <input type="checkbox" class="form-check-input">
                            Keep me signed in
                        </label>
                    </div>
                    <a href="<?= $this->url('user/default', ['controller' => 'Index', 'action' => 'recovered-password']);?>" class="auth-link text-black">Forgot password?</a>
                </div>
                <div class="text-center mt-4 font-weight-light">
                    Don't have an account? <a href="<?= $this->url('user/default', ['controller' => 'Index', 'action' => 'register']);?>" class="text-primary">Create</a>
                </div>
            <?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>