<?= $this->doctype() ?>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <?= $this->headTitle('voliveiras Shopping')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- plugins:css -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        //inject:css
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('vendors/base/vendor.bundle.base.css'))
        ->prependStylesheet($this->basePath('vendors/mdi/css/materialdesignicons.min.css'))
    ?>
    <!-- endinject -->
    <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth px-0">
            <?= $this->content ?>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<?= $this->headScript()
    ->prependFile($this->basePath('js/template.js'))
    ->prependFile($this->basePath('js/hoverable-collapse.js'))
    ->prependFile($this->basePath('js/off-canvas.js'))
    ->prependFile($this->basePath('vendors/base/vendor.bundle.base.js'))
?>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
<!-- endinject -->
</body>

</html>
