<div class="row flex-grow">
    <div class="col-lg-6 d-flex align-items-center justify-content-center">
        <div class="auth-form-transparent text-left p-3">
            <div class="brand-logo">
                <img src="images/logo.svg" alt="logo">
            </div>
            <h4>Informe o e-mail cadastrado</h4>
            <?php
            echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
            echo $this->flashMessenger()->render('success', ['alert alert-success alert-dismissible']);
            ?>
            <?php echo $this->form()->openTag($this->form); ?>
            <?php echo $this->formHidden($this->form->get('csrf'));?>
            <div class="form-group <?php echo $this->formElementErrors($this->form->get('email')) ? 'has-error' : ''; ?> has-feedback">
                <?php echo $this->form->get('email')->getLabel();?>
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                              <span class="input-group-text bg-transparent border-right-0">
                                <i class="mdi mdi-email-outline text-primary"></i>
                              </span>
                    </div>
                    <?php echo $this->formEmail($this->form->get('email'));?>
                    <?php echo $this->formElementErrors($this->form->get('email')); ?>
                </div>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">Enviar</button>
            </div>
            <?php echo $this->form()->closeTag($this->form); ?>
            <?php $this->flashMessenger()->clearMessagesFromContainer(true); ?>
        </div>
    </div>
    <div class="col-lg-6 register-half-bg d-flex flex-row">
        <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2018  All rights reserved.</p>
    </div>