<div class="row flex-grow">
    <div class="col-lg-6 d-flex align-items-center justify-content-center">
        <div class="auth-form-transparent text-left p-3">
            <div class="brand-logo">
                <img src="images/logo.svg" alt="logo">
            </div>
            <h4>New here?</h4>
            <h6 class="font-weight-light">Join us today! It takes only few steps</h6>
            <?php
                echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
                echo $this->flashMessenger()->render('success', ['alert alert-success alert-dismissible']);
            ?>
            <?php echo $this->form()->openTag($this->form); ?>
             <?php echo $this->formHidden($this->form->get('csrf'));?>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('username')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('username')->getLabel();?>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                          <span class="input-group-text bg-transparent border-right-0">
                            <i class="mdi mdi-account-outline text-primary"></i>
                          </span>
                        </div>
                        <?php echo $this->formText($this->form->get('username'));?>
                        <?php echo $this->formElementErrors($this->form->get('username')); ?>
                    </div>
                </div>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('email')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('email')->getLabel();?>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                              <span class="input-group-text bg-transparent border-right-0">
                                <i class="mdi mdi-email-outline text-primary"></i>
                              </span>
                        </div>
                        <?php echo $this->formEmail($this->form->get('email'));?>
                        <?php echo $this->formElementErrors($this->form->get('email')); ?>
                    </div>
                </div>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('country')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('country')->getLabel();?>
                    <?php echo $this->formSelect($this->form->get('country'));?>
                    <?php echo $this->formElementErrors($this->form->get('country')); ?>
                </div>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('password')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('password')->getLabel();?>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                          <span class="input-group-text bg-transparent border-right-0">
                            <i class="mdi mdi-lock-outline text-primary"></i>
                          </span>
                        </div>
                        <?php echo $this->formPassword($this->form->get('password'));?>
                        <?php echo $this->formElementErrors($this->form->get('password')); ?>
                    </div>
                </div>
                <div class="form-group <?php echo $this->formElementErrors($this->form->get('replypassword')) ? 'has-error' : ''; ?> has-feedback">
                    <?php echo $this->form->get('replypassword')->getLabel();?>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                              <span class="input-group-text bg-transparent border-right-0">
                                <i class="mdi mdi-lock-outline text-primary"></i>
                              </span>
                        </div>
                        <?php echo $this->formPassword($this->form->get('replypassword'));?>
                        <?php echo $this->formElementErrors($this->form->get('replypassword')); ?>
                    </div>
                </div>
                <div class="mb-4">
                    <div class="form-check <?php echo $this->formElementErrors($this->form->get('idcondition')) ? 'has-error' : ''; ?> has-feedback">
                        <label class="form-check-label text-muted">
                            <?php echo $this->formCheckbox($this->form->get('idcondition'));?>
                            <?php echo $this->form->get('idcondition')->getLabel();?>
                        </label>
                        <?php echo $this->formElementErrors($this->form->get('idcondition')); ?>
                    </div>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">SIGN UP</button>
                </div>
                <div class="text-center mt-4 font-weight-light">
                    Already have an account? <a href="<?= $this->url('auth.login');?>" class="text-primary">Login</a>
                </div>
            <?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
    <div class="col-lg-6 register-half-bg d-flex flex-row">
        <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2018  All rights reserved.</p>
    </div>